apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: podman-runner
  namespace: podman-demo
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: podman-runner
  namespace: podman-demo
spec:
  source:
    git:
      uri: https://github.com/haircommander/openshift-nested-containers.git
      ref: main
    contextDir: "podman-image"
  strategy:
    dockerStrategy:
      dockerfilePath: "./podman-runner.Containerfile"
  output:
    to:
      kind: ImageStreamTag
      name: podman-runner:latest
