apiVersion: v1
kind: Pod
metadata:
 name: nested-podman
 annotations:
   io.kubernetes.cri-o.Devices: "/dev/fuse,/dev/net/tun"
spec:
  hostUsers: false
  containers:
  - name: nested-podman
    image: quay.io/rh-ee-atokubi/nested-podman
    args: ["tail", "-f", "/dev/null"]
    imagePullPolicy: Always
    securityContext:
      runAsUser: 1000
      procMount: Unmasked
      capabilities:
        add:
          - "SETUID"
          - "SETGID"
