apiVersion: v1
kind: Pod
metadata:
 name: nested-podman2
 annotations:
   io.kubernetes.cri-o.Devices: "/dev/fuse,/dev/net/tun"
spec:
  hostUsers: false
  dnsPolicy: None
  dnsConfig:
    nameservers:
      - 1.1.1.1
  containers:
  - name: nested-podman
    image: quay.io/rh-ee-atokubi/nested-podman
    command: ["sleep", "100000"]
    imagePullPolicy: Always
    securityContext:
      runAsUser: 1000
      procMount: Unmasked
      capabilities:
        add:
          - "SETUID"
          - "SETGID"
      seccompProfile:
        type: Unconfined
      seLinuxOptions:
        type: "container_engine_t"
