apiVersion: v1
kind: Pod
metadata:
 name: nested-podman
 namespace: podman-demo
 annotations:
   io.kubernetes.cri-o.Devices: "/dev/fuse"
spec:
  hostUsers: false
  imagePullPolicy: Always
  containers:
  - name: nested-podman
    image: image-registry.openshift-image-registry.svc:5000/podman-demo/podman-runner:latest
    args: ["tail", "-f", "/dev/null"]
    securityContext:
      runAsUser: 1000
      procMount: Unmasked
      capabilities:
        add:
        - "ALL"
