apiVersion: v1
kind: Pod
metadata:
  name: userns
  annotations:
    io.kubernetes.cri-o.Devices: "/dev/fuse,/dev/net/tun"
spec:
  containers:
  - name: userns
    imagePullPolicy: Always
    image: quay.io/haircommander/podman-system-tests
    args:
    - sleep
    - "1000000"
    securityContext:
      runAsUser: 1000
      seLinuxOptions:
        type: "container_engine_t"
      capabilities:
        add:
          - "SETUID"
          - "SETGID"
      appArmorProfile:
        type: Unconfined
  hostUsers: false
  securityContext:
    sysctls:
    - name: net.ipv4.ping_group_range
      value: "0           1000"
