apiVersion: v1
kind: Pod
metadata:
  name: userns
  annotations:
    io.kubernetes.cri-o.Devices: "/dev/fuse,/dev/net/tun"
spec:
  containers:
  - name: userns
    image: quay.io/haircommander/podman-system-tests:systemd
    args:
    - sleep
    - "1000000"
    securityContext:
      runAsUser: 0
      seLinuxOptions:
        type: "container_engine_t"
      capabilities:
        add:
          - "SETUID"
          - "SETGID"
  hostUsers: false
  securityContext:
    sysctls:
    - name: net.ipv4.ping_group_range
      value: "0           1000"
