apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-sysctl
  labels:
    machineconfiguration.openshift.io/role: worker 
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,W2NyaW8ucnVudGltZV0KZGVmYXVsdF9zeXNjdGxzID0gWyJuZXQuaXB2NC5pcF9mb3J3YXJkPTEiXQo=
        mode: 420
        overwrite: true
        path: /etc/crio/crio.conf.d/99-sysctl.conf
  osImageURL: ""
