apiVersion: v1
kind: Pod
metadata:
  name: userns
  annotations:
    io.kubernetes.cri-o.Devices: "/dev/fuse,/dev/net/tun"
spec:
  containers:
  - name: userns
    image: quay.io/haircommander/podman-system-tests:systemd
    imagePullPolicy: Always
    command: /sbin/init
    securityContext:
      runAsUser: 0
      seLinuxOptions:
        type: "container_engine_t"
      capabilities:
        add:
          - "SETUID"
          - "SETGID"
  hostUsers: false
  securityContext:
    sysctls:
    - name: net.ipv4.ping_group_range
      value: "0           1000"
        #- name: net.ipv6.conf.default.autoconf
        #  value: "0"
        #- name: net.ipv4.conf.default.route_localnet
        #  value: "0"
        #- name: net.ipv4.ip_forward
        #  value: "1"
        #- name: net.ipv6.conf.all.forwarding
        #  value: "1"
        #- name: net.ipv4.conf.default.forwarding
        #  value: "1"
        #- name: net.ipv6.conf.default.accept_dad
        #  value: "0"
        #- name: net.ipv6.conf.default.accept_ra
        #  value: "0"
        #- name: sys.net.ipv4.conf.default.arp_notify
        #  value: "1"
