apiVersion: v1
kind: Pod
metadata:
  name: userns
spec:
  containers:
  - name: userns
    image: registry.access.redhat.com/ubi9
    command: ["sleep", "1000"]
    securityContext:
      capabilities:
        drop: ["ALL"]
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
      runAsUser: 1024
      runAsGroup: 1024
  hostUsers: false
