FROM registry.access.redhat.com/ubi9
ENV BUILDAH_ISOLATION=chroot
RUN dnf --disableplugin=subscription-manager install -y openssl compat-openssl11 libbrotli git tar shadow-utils bash zsh podman buildah skopeo ; \
    dnf update -y ; \
    dnf clean all ; \
    #
    # Setup for root-less podman
    #
    setcap cap_setuid+ep /usr/bin/newuidmap ; \
    setcap cap_setgid+ep /usr/bin/newgidmap ;
#     touch /etc/subgid /etc/subuid ; \
#     chown 0:0 /etc/subgid ; \
#     chown 0:0 /etc/subuid ; \
#     chown 0:0 /etc/passwd ; \
#     chown 0:0 /etc/group ; \
#    chmod +x /entrypoint.sh ; \
#    chmod -R g=u /etc/passwd /etc/group /etc/subuid /etc/subgid /home ${WORK_DIR}
RUN useradd podman && \
    echo -e "podman:1:999\npodman:1001:64535" > /etc/subuid && \
    echo -e "podman:1:999\npodman:1001:64535" > /etc/subgid
# Copy & modify the defaults to provide reference if runtime changes needed.
# Changes here are required for running with fuse-overlay storage inside container.
RUN sed -i -e 's|^#mount_program|mount_program|g' \
           -e '/additionalimage.*/a "/var/lib/shared",' \
           -e 's|^mountopt[[:space:]]*=.*$|mountopt = "nodev,fsync=0"|g' \
           /etc/containers/storage.conf

RUN dnf -y makecache && \
        dnf -y update && \
        dnf install -y \
        file \
        git \
        go \
        gpgme-devel \
        httpd-tools \
        jq \
        libseccomp-devel \
        make \
        nc \
        openssl \
        procps \
        python-yaml \
        skopeo \
        slirp4netns \
        socat \
	xz
RUN git clone https://github.com/bats-core/bats-core.git && \
	cd bats-core && \
	./install.sh /usr/local
USER podman
RUN mkdir -p /home/podman/go/src/github.com/containers && \
        cd $_ && \
        git clone https://github.com/containers/podman
WORKDIR /home/podman/go/src/github.com/containers/podman
RUN make bin/podman-testing && make bin/podman
COPY --chown=podman:podman --chmod=755 entrypoint.sh /
COPY test.bash test.bash
RUN ./test.bash
USER root
RUN mkdir -p /run/user/1000 && chown podman:podman $_
ADD /containers.conf /etc/containers/containers.conf
RUN mkdir -p /home/podman/.local/share/containers && \
    chown podman:podman -R /home/podman && \
    chmod 644 /etc/containers/containers.conf
ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "tail", "-f", "/dev/null" ]
