# largely based on https://github.com/containers/image_build/blob/main/podman/Containerfile
FROM registry.fedoraproject.org/fedora:latest

RUN dnf -y makecache && \
    dnf -y update && \
    dnf -y install go bats git 'dnf-command(builddep)' iproute gcc \
		glib2-devel glibc-devel glibc-static golang git-core gpgme-devel libassuan-devel \
		libgpg-error-devel libseccomp-devel libselinux-devel pkgconfig \
		ostree-devel shadow-utils-subid-devel containers-common-extra \
		make man-db systemd systemd-devel catatonit conmon \
		# from https://catalog.redhat.com/software/containers/ubi9-init/6183297540a2d8e95c82e8bd?architecture=amd64&image=65e0aca88b7d6c2795cea14c&container-tabs=dockerfile
		procps-ng systemd && \
	dnf clean all && \
    rm -rf /var/cache /var/log/dnf* /var/log/yum.* \
	rpm --restore shadow-utils


CMD ["/sbin/init"]

STOPSIGNAL SIGRTMIN+3

#mask systemd-machine-id-commit.service - partial fix for https://bugzilla.redhat.com/show_bug.cgi?id=1472439
# from https://catalog.redhat.com/software/containers/ubi9-init/6183297540a2d8e95c82e8bd?architecture=amd64&image=65e0aca88b7d6c2795cea14c&container-tabs=dockerfile
RUN systemctl mask systemd-remount-fs.service dev-hugepages.mount \
	sys-fs-fuse-connections.mount systemd-logind.service \
	getty.target console-getty.service systemd-udev-trigger.service \
	systemd-udevd.service systemd-random-seed.service systemd-machine-id-commit.service && \
	# from https://github.com/robertdebock/docker-fedora-systemd/blob/master/Dockerfile
    (cd /lib/systemd/system/sysinit.target.wants/ ; for i in * ; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i ; done) ; \
    rm -f /lib/systemd/system/multi-user.target.wants/* ;\
    rm -f /etc/systemd/system/*.wants/* ;\
    rm -f /lib/systemd/system/local-fs.target.wants/* ; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev* ; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl* ; \
    rm -f /lib/systemd/system/basic.target.wants/* ;\
    rm -f /lib/systemd/system/anaconda.target.wants/*

RUN useradd podman; \
	echo -e "podman:1:999\npodman:1001:64535" > /etc/subuid; \
	echo -e "podman:1:999\npodman:1001:64535" > /etc/subgid;

ADD /containers.conf /etc/containers/containers.conf
ADD /podman-containers.conf /home/podman/.config/containers/containers.conf

RUN mkdir -p /home/podman/go/src/github.com/containers && cd $_ && git clone https://github.com/containers/podman


RUN mkdir -p /home/podman/.local/share/containers && \
    chown podman:podman -R /home/podman && \
    chmod 644 /etc/containers/containers.conf

# Copy & modify the defaults to provide reference if runtime changes needed.
# Changes here are required for running with fuse-overlay storage inside container.
RUN sed -e 's|^#mount_program|mount_program|g' \
           -e '/additionalimage.*/a "/var/lib/shared",' \
           -e 's|^mountopt[[:space:]]*=.*$|mountopt = "nodev,fsync=0"|g' \
           /usr/share/containers/storage.conf \
           > /etc/containers/storage.conf

# Setup internal Podman to pass subscriptions down from host to internal container
RUN printf '/run/secrets/etc-pki-entitlement:/run/secrets/etc-pki-entitlement\n/run/secrets/rhsm:/run/secrets/rhsm\n' > /etc/containers/mounts.conf

# Note VOLUME options must always happen after the chown call above
# RUN commands can not modify existing volumes
VOLUME /var/lib/containers
VOLUME /home/podman/.local/share/containers

RUN mkdir -p /var/lib/shared/overlay-images \
             /var/lib/shared/overlay-layers \
             /var/lib/shared/vfs-images \
             /var/lib/shared/vfs-layers && \
    touch /var/lib/shared/overlay-images/images.lock && \
    touch /var/lib/shared/overlay-layers/layers.lock && \
    touch /var/lib/shared/vfs-images/images.lock && \
    touch /var/lib/shared/vfs-layers/layers.lock

ENV _CONTAINERS_USERNS_CONFIGURED="" \
    BUILDAH_ISOLATION=chroot
